---
- include: rules.yml

- include: persist-debian.yml
  when: 
    - ansible_os_family == 'Debian'
    - firewall_persist_rules == true

- include: persist-redhat.yml
  when: 
    - ansible_os_family == 'RedHat'
    - firewall_persist_rules == true
